Train config fix
dsi-clinic/CMAP pull request #137
Opened 2024-11-04 21:06 UTC by ms475

Fixed issues with importing config in intialize_dataset. The function now accepts the config object as an input.

2024-11-05 18:43 UTC, annawoodard approved these changes
Great thank you

2024-11-05 18:44 UTC, annawoodard requested changes
Sorry missed this, can you remove the notebook from the PR? Thanks

2024-11-07 03:16 UTC, cassietang717 approved these changes

2024-11-08 02:25 UTC, ms475 commented
For some reason I am completely unable to remove this file! I will create another pull request

2024-11-08 02:25 UTC, closed without merging